uploads = []

[[generated]]
id = "IGvBsBMHKS2FexivA-Agd"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "3e4tq5MnUeaPu3QUiDRgO"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "New PinnboxIO App Icon"

[[outputs]]
id = "iseJABsVkJdUM1Fjkys_H"
uri = "file://pinnboxio-mobile-build.zip"
type = "unspecified"
title = "PinnboxIO Mobile Build Files (v4 - Fixed)"
