// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/storage-redesign/DropboxStyle.tsx": () => import("../components/mockups/storage-redesign/DropboxStyle.tsx"),
  "./components/mockups/storage-redesign/ModernGrid.tsx": () => import("../components/mockups/storage-redesign/ModernGrid.tsx"),
  "./components/mockups/mobile-layout/BottomNav.tsx": () => import("../components/mockups/mobile-layout/BottomNav.tsx"),
  "./components/mockups/mobile-layout/Current.tsx": () => import("../components/mockups/mobile-layout/Current.tsx")
};
